
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zctpkaykssixfohmzokq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdHBrYXlrc3NpeGZvaG16b2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjA3NDMsImV4cCI6MjA2MDg5Njc0M30.pq2Ksx0gJoaO1h3AHmhFfMQTf-xRHdgDizFdV9bk3RY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'finconnect-auth',
  },
  global: {
    fetch: (url, options) => {
      return fetch(url, options).catch(err => {
        console.error('Supabase request failed:', err);
        throw err;
      });
    }
  }
});
